version: "3.8"

services:
  triangle-demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: npm start
    ports:
      - "3000:3000"

  cypress:
    image: "cypress/base:20.9.0"
    depends_on:
      - triangle-demo
    environment:
      - CYPRESS_baseUrl=http://triangle-demo:3000
      - CYPRESS_VIDEO=false
    working_dir: /e2e
    command: bash -c "sleep 20 && npx cypress install && npx cypress run"
    volumes:
      - ./:/e2e
